package crypto

import (
	"crypto/hmac"
	"crypto/sha256"
	"math/big"
)

// GenerateK_RFC6979 generates deterministic k based on RFC 6979
// Reference: https://tools.ietf.org/html/rfc6979#section-3.2
func GenerateK_RFC6979(n *big.Int, privateKey *big.Int, messageHash *big.Int) *big.Int {
	// Initialize HMAC-DRBG
	// k = H(x || h1)

	// Convert inputs to bytes
	privBytes := privateKey.Bytes()
	hashBytes := messageHash.Bytes()

	// Pad to ensure consistent length (32 bytes / 256 bits)
	keyLen := (n.BitLen() + 7) / 8
	if len(privBytes) < keyLen {
		padding := make([]byte, keyLen-len(privBytes))
		privBytes = append(padding, privBytes...)
	}
	if len(hashBytes) < keyLen {
		padding := make([]byte, keyLen-len(hashBytes))
		hashBytes = append(padding, hashBytes...)
	}

	v := make([]byte, 32)
	k := make([]byte, 32)
	for i := range v {
		v[i] = 0x01
	}
	for i := range k {
		k[i] = 0x00
	}

	// 3.2.d: K = HMAC_K(V || 0x00 || int2octets(x) || bits2octets(h1))
	mac := hmac.New(sha256.New, k)
	mac.Write(v)
	mac.Write([]byte{0x00})
	mac.Write(privBytes)
	mac.Write(hashBytes)
	k = mac.Sum(nil)

	// 3.2.e: V = HMAC_K(V)
	mac = hmac.New(sha256.New, k)
	mac.Write(v)
	v = mac.Sum(nil)

	// 3.2.f: K = HMAC_K(V || 0x01 || ... )
	mac = hmac.New(sha256.New, k)
	mac.Write(v)
	mac.Write([]byte{0x01})
	mac.Write(privBytes)
	mac.Write(hashBytes)
	k = mac.Sum(nil)

	// 3.2.g: V = HMAC_K(V)
	mac = hmac.New(sha256.New, k)
	mac.Write(v)
	v = mac.Sum(nil)

	// 3.2.h: Generate T
	for {
		var t []byte
		// We just need generated bytes >= qlen
		// Since qlen is 256 bits (32 bytes) and SHA256 is 32 bytes, we assume one round is enough usually?
		// But RFC says loop.

		mac = hmac.New(sha256.New, k)
		mac.Write(v)
		v = mac.Sum(nil)
		t = append(t, v...)

		// Convert T to integer k_candidate
		kInt := new(big.Int).SetBytes(t)

		// Check if k is valid in [1, n-1]
		if kInt.Cmp(big.NewInt(0)) > 0 && kInt.Cmp(n) < 0 {
			return kInt
		}

		// K = HMAC_K(V || 0x00)
		mac = hmac.New(sha256.New, k)
		mac.Write(v)
		mac.Write([]byte{0x00})
		k = mac.Sum(nil)

		// V = HMAC_K(V)
		mac = hmac.New(sha256.New, k)
		mac.Write(v)
		v = mac.Sum(nil)
	}
}
